server:
  port: 8080
  tomcat:
    threads:
      max: 200
      min-sparse: 20
    accept-count: 100
    max-connections: 8192
    connection-timeout: 20000
spring:
  application:
    name: flashsale

  datasource:
    url: jdbc:postgresql://localhost:5432/flashsale_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 3000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: FlashSaleHikariCP
  jpa:
    hibernate:
      ddl-auto: validate 
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  data:
    redis:
      host: choice-marlin-177093.upstash.io
      port: 6379
      password: gQAAAAAAArPFAAIgcDE5M2E0YWZlM2ViM2I0MGI5YjVlMzg5M2EwOWEyMWU2Yg
      ssl:
          enabled: true

  rabbitmq:
    addresses: amqps://lbhmielu:26jTedW0k7EYJzgtQUQPAJUkD8dnRQXs@armadillo.rmq.cloudamqp.com/lbhmielu