server:
  port: 8080

spring:
  application:
    name: flashsale

  datasource:
    url: jdbc:postgresql://localhost:5432/flashsale_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: choice-marlin-177093.upstash.io
      port: 6379
      password: ggAAAAAAArPFAAIgcDHilUk3S1gETiTF3m6I4le4sAHaEa41zDa2ylQmYRfp4A
      ssl:
          enable:true  

  rabbitmq:
    addresses: amqps://lbhmielu:26jTedW0k7EYJzgtQUQPAJUkD8dnRQXs@armadillo.rmq.cloudamqp.com/lbhmielu